  medusa:
    build: .
    container_name: medusa_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
      - "5173:5173"
      
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:Gamble1504@medusa-sql-5zda3c:5432/medusa
      - REDIS_URL=redis://default:Gamble1504@medusa-redis-qx7on1:6379
      - JWT_SECRET=HUU5FVCOfzahKRb1h4G7CQ0rwr1Dzy8LH4ioPb7bJg0=
      - COOKIE_SECRET=p8TFUhOY/FXDSBtLoZYLlIMszLdQkcB4/8UTj1NRsqg=
      - STORE_CORS=http://192.168.0.235:8000
      - ADMIN_CORS=http://192.168.0.235:9000
      - AUTH_CORS=http://192.168.0.235:8000,http://192.168.0.235:9000
    networks:
      - medusa_network

  storefront:
    build: .
    container_name: medusa_storefront
    restart: unless-stopped
    depends_on:
      - medusa
    ports:
      - "8000:8000"
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://medusa:9000
    entrypoint: ["./start-storefront.sh"]
    networks:
      - medusa_network
